### ISSUE TITLE
Consider lowering IPHONEOS_DEPLOYMENT_TARGET to 8.1

### ISSUE THREAD

**Issue by DanielAsher** [arkverse/UIClosures#3]
Unless there is good reason I believe lowering IPHONEOS_DEPLOYMENT_TARGET to 8.1 would allow UIClosures to be integrated more easily into iOS projects.

I would be glad to arrange a PR if it is helpful.

**Comment by zaiddag** [comment]
would be appreciated :)

**Comment by zaiddag** [comment]
done! thank you :)
